os: linux
services:
    - docker
language: ruby

before_install:
    - docker build -t softqa1993/docker-react -f Dockerfile.dev .

script:
    - docker run softqa1993/docker-react npm run test -- --coverage
