os: linux
services:
    - docker
language: ruby

before_install:
    - docker build -t softqa1993/docker-react -f Dockerfile.dev .

script:
    - docker run softqa1993/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-1-661508924726"
    bucket_path: "docker-react"
    on:
        brach: master

    access_key_id: "$AWS_ACCESS_KEY"  
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
